# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ocelot Consulting
email: info@ocelotconsulting.com
description: > # "Ocelot Consulting specializes in cloud technologies, custom application development and enterprise security.
  Ocelot Consultants are certified AWS Solution Architects and have experience migrating enterprise applications and data for
  Fortune 500 companies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ocelotconsulting.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]
paginate: 5
paginate_path: "/blog/page:num/"
sass:
  style: compact # possible values: nested expanded compact compressed

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ocelot_llc
  - title: github
    url: https://github.com/ocelotconsulting/
  - title: linkedin
    url: https://www.linkedin.com/company/ocelot-consulting-llc
  - title: facebook
    url: https://facebook.com/ocelotconsultingllc/
  - title: rss
    url: /feed.xml
  - title: slack
    url: http://slack-registration.foxeared.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
